### PR TITLE
Refactor 2.0

### PR DESCRIPTION
**Pull request by mnunberg**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
@mnunberg pls remove all the prints from the pytests and from the code itself.

In addition I am getting this crash when running the pytests:
`
test_ext:testExt
	[ERROR]
	Unhandled exception: Cannot establish connection Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>: Error 111 connecting to localhost:6379. Connection refused.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/RLTest/__main__.py", line 415, in _runTest
    fn()
  File "/home/meir/work/RediSearch/src/pytest/test_ext.py", line 24, in testExt
    env = Env(moduleArgs='EXTLOAD %s' % EXTPATH)
  File "build/bdist.linux-x86_64/egg/RLTest/env.py", line 166, in __init__
    self.start()
  File "build/bdist.linux-x86_64/egg/RLTest/env.py", line 208, in start
    self.envRunner.startEnv()
  File "build/bdist.linux-x86_64/egg/RLTest/redis_std.py", line 159, in startEnv
    self.waitForRedisToStart(con)
  File "build/bdist.linux-x86_64/egg/RLTest/redis_std.py", line 101, in waitForRedisToStart
    wait_for_conn(con, retries=1000 if self.debugger else 200)
  File "build/bdist.linux-x86_64/egg/RLTest/utils.py", line 17, in wait_for_conn
    raise Exception('Cannot establish connection %s: %s' % (conn, err))
Exception: Cannot establish connection Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>: Error 111 connecting to localhost:6379. Connection refused.
`
Pls check this out.

**Comment by MeirShpilraien** [comment]
Still failing even from the build dir and when I am setting

**Comment by mnunberg** [comment]
It works fine for me -- crash was related to something else I hadn't yet pushed.

Maybe you have another .so hiding in the source directory somewhere, and it might be looking for that? Clean your directory and start over.

Can you run with `--vg` or `-i` to see what's wrong, since I cannot reproduce it

**Comment by MeirShpilraien** [comment]
@mnunberg it was my mistake, I got it working, lets just remove all the prints and I think we are good to go.

Lets also create 1.4.3 branch before merging.

**Comment by mnunberg** [comment]
@MeirShpilraien 1.4.3 branch is at https://github.com/RedisLabsModules/RediSearch/tree/1.4.3-tip

**Pull request merged**
