### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by merl-dev**
I found a few minor issues that prevented compilation.  Ran a few tests on the compiled module and seems to be fine.

### CODE REVIEW

**Comment by dvirsky** [comment]
those are really odd that they got in, probably during yesterday's commit of indentation fixes. anyway thanks, I'm merging these.

**Comment by merl-dev** [comment]
txs, where are you located?

**Comment by dvirsky** [comment]
Tel Aviv. You?

**Comment by merl-dev** [comment]
same, cool!

**Comment by dvirsky** [comment]
glad you're interested in this. BTW we're hosting a meetup about modules in a few weeks, I hope you'll attend. I think it's going to be in 18/7.

**Comment by merl-dev** [comment]
sounds good.  I have been working with Redis in production for about 2 years, now on sabbatical devoted almost exclusively to Redis.  I am a Julia coder, right now undertaking massive refak of the Redis.jl package and will be issuing a RedisModules.jl soon after to interface with all these very cool modules, plus 2 modules that I am presently working on.  My focus is streaming/online stats for online media and finance + nonstationarity TS modelling.  I believe this could be a good contender in what is becoming a very competitive environment.  
Will definitely attend the meetup.

**Comment by merl-dev** [comment]
you have a redislabs email?

**Comment by dvirsky** [comment]
yep, dvir at ...

**Comment by merl-dev** [comment]
sent a linked in invite, Yaakov Borstein

**Pull request merged**
