### PR TITLE
Removed benchmark & Makefile fixes

### PR DESCRIPTION
**Pull request by amallia**
When compiling on MacOS I get a linking error.
`ld: library not found for -lcrt0.o`

This is a common MacOS issue for static linking: [Link1](https://nelsonslog.wordpress.com/2013/04/24/macos-doesnt-support-static-binaries/), [Link2](http://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag)

### CODE REVIEW

**Comment by dvirsky** [comment]
Actually, Antonio, while you're at it - instead of this fix, please just remove the entire benchmark folder, it was some experiment that got committed by accident and I forgot to delete it.

**Comment by amallia** [comment]
Don't we need to run benchmarks?

**Comment by dvirsky** [comment]
We do, but these are not actual useful benchmarks.

**Comment by dvirsky** [comment]
My benchmarks aren't automated, I'm running them manually. It's a good idea to automate them actually.

**Comment by amallia** [comment]
I have added some fixes to the Makefiles. 
'Make test' doesn't set REDIS_MODULE_TARGET if running it from main directory

**Comment by dvirsky** [comment]
that's on purpose, tests are not running inside a redis module!

**Comment by amallia** [comment]
So far if you run `make test` from the source directory you get a warning.
```
test_range.c:115:3: warning: implicit declaration of function 'RMUTil_InitAlloc' is invalid in C99 [-Wimplicit-function-declaration]
  RMUTil_InitAlloc();
  ^
1 warning generated.
```

**Comment by dvirsky** [comment]
I'm seeing too many failures on Travis. I don't think it's related but I'm waiting until I finish the current branch I'm working on, and then I'll merge this and stabilize the builds.

**Pull request closed without merging**
