### PR TITLE
fix: Minor grammar fix inside printf

### PR DESCRIPTION
**Pull request by joeirimpan**

### CODE REVIEW

**Comment by joeirimpan** [comment]
eagerly waiting for spellcheck module on client libraries

**Comment by MeirShpilraien** [comment]
@mnunberg any idea why circle fails on packaging?

**Comment by mnunberg** [comment]
It looks like something to do with the package name. It’s not being seen by RAMP, it seems like. I’m unsure what has changed, if any, between versions?

**Comment by MeirShpilraien** [comment]
@joeirimpan Pls try to pull from master, the packaging should work now.

**Pull request merged**
