### PR TITLE
Add GC_SCANSIZE configuration

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by itamarhaber** [comment]
Don't forget to add this to the configuration.md file

**Comment by mnunberg** [comment]
Please use `GC_SCANSIZE` or something similar for the option name; @itamarhaber this will probably be a private setting.

**Comment by itamarhaber** [comment]
@mnunberg there is no privacy in OSS :)

All configuration settings are public and should be documented. Warnings may be applied, in docus, when needed.

**Comment by mnunberg** [comment]
Oh, also change the `docsToScanAfterEachIteration` variable to `gcScanSize` or similar. Maybe also change the macro name itself.

**Pull request merged**
