### PR TITLE
Fix link to DESIGN.md in the README

### PR DESCRIPTION
**Pull request by mheiber**
Link was broken.
Change from "DESIGN.md" to "docs/DESIGN.md"

### CODE REVIEW

**Comment by dvirsky** [comment]
heh, that was quick, I changed the folder structure only a couple of hours ago :)

**Comment by dvirsky** [comment]
oh, actually your fix didn't solve it, you changed the text, not the actual link.

**Comment by dvirsky** [comment]
fixed it myself, but thanks for catching it!

**Comment by mheiber** [comment]
@dvirsky no problem, cool work you're doing on this module! Sorry I didn't check my fix carefully enough, thanks for catching!

**Pull request merged**
