### PR TITLE
Inherit CFLAGS & LDFLAGS from outside environment.

### PR DESCRIPTION
**Pull request by lamby**
In Debian we use the dpkg-buildflags mechanism to control
enabling/disabling of hardening-related buildflags such as relro, PIE
etc.

However, the current Makefile currently ignores those for CFLAGS and
then ignored them when linking.

### CODE REVIEW

**Comment by lamby** [comment]
``CLFLAGS``? ``CFLAGS``.

**Comment by mnunberg** [comment]
Seems this fails because `$MODULE_ARTIFACT` isn't set to anything. Otherwise CI looks good.

**Comment by lamby** [comment]
> Seems this fails because $MODULE_ARTIFACT isn't set to anything

Mmm, that seems unrelated to this PR, so shouldn't block merge AFACT?

**Comment by dvirsky** [comment]
@mnunberg the problem is that we're hiding some environment variables from PRs, this is a security measure (otherwise PRs can add a line to print our S3 credentials which are exposed as env vars to builds). This means PRs never build successfully. I'll see what I can do to mitigate this.

**Comment by dvirsky** [comment]
@lamby for some reason github's useless conflict editor can't resolve the stupid conflict here, so I'm just applying this manually onto master. However I'm not changing `$LD` to `$CC` since it breaks the build on Mac Os.

**Comment by lamby** [comment]
> I'm not changing $LD to $CC since it breaks the build on Mac Os.

Right, but then you can't use the linker pass-through variables that `dpkg-buildflags` exports, rendering the change somewhat useless. :(

**Comment by dvirsky** [comment]
you want to create an OS based variable for the linker? I'll live with that.

**Comment by lamby** [comment]
> you want to create an OS based variable for the linker? I'll live with that.

Don't quite follow that, sorry :)

**Comment by dvirsky** [comment]
```
LINKER=$LD
ifneq ($(uname_S),Darwin)
  LINKER=$CC
endif
```

**Comment by dvirsky** [comment]
@lamby try it now and see if it works fine

**Pull request closed without merging**
