### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by amallia**
* Removed unused code
* Fixed format 
* Added missing include
* Removed side-effects in assert

### CODE REVIEW

**Comment by dvirsky** [comment]
@amallia would you mind resolving the conflicts?

**Comment by amallia** [comment]
@dvirsky done. Thanks

**Comment by amallia** [comment]
Any problem with this PR? Anything else to be changed?

**Comment by dvirsky** [comment]
@amallia not really, I'm just in the middle of a big change and no time to merge stuff. I hope it won't create too much collisions with the current work. Which is a big game changer BTW - I'm letting the search request be concurrent, i.e. if you have a very long query, other shorter ones will execute while it is processing.

**Comment by dvirsky** [comment]
Merged, thanks Antonio

**Pull request merged**
