### PR TITLE
Little code cleanup proposal/compilation warning

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mnunberg** [comment]
@devnexen please digitally sign the CLA so we can submit this

**Comment by devnexen** [comment]
Already did the status seems pending.

**Comment by mnunberg** [comment]
I think I know what the problem is: You seem to have two github accounts, and the commit is registered under one, but the PR is registered under the other. Can you make sure you've signed the CLA under both accounts?

**Comment by devnexen** [comment]
Sorry I just used wrong account in fact. fixed !

**Pull request merged**
