### PR TITLE
see #621, fixed, reset aCtx flags if needed

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
- [ ] cherry pick to master

**Comment by MeirShpilraien** [comment]
@mnunberg can I merge this one?

**Comment by mnunberg** [comment]
I think a better solution would be something like:
```c
aCtx->stateFlags &= ~(ACTX_F_TEXTINDEXED....
```

rather than if-else

Basically, clear the previous document-related flags when we enter the function.

**Comment by MeirShpilraien** [comment]
@mnunberg I pushed another commit.

**Comment by mnunberg** [comment]
This is going to go in with multitype

**Comment by MeirShpilraien** [comment]
@mnunberg did you eventually took this to the multitype branch?

**Pull request merged**
