### PR TITLE
Query attribute

### PR DESCRIPTION
**Pull request by dvirsky**
This PR adds query and sub query attributes with the syntax: `expression => {$attr:value;...}`

## NOTE: The PR is still missing documentation.

Supported attributes:

* weight
* slop
* inorder

e.g.:

```
@title:foo => {$weight: 1} | @body:bar => {$weight: 2}
(foo bar) => {$slop: 0} (bar baz) => {$slop: 2} 

etc etc
```

### CODE REVIEW

**Comment by mnunberg** [comment]
This was simpler than I expected

**Comment by mnunberg** [comment]
I am not crazy about having the weight added to each and every index reader function. It seems the only purpose is for it to later populate the index result with the same weight attribute. Might it be better to provide a factory for the search result generation.

**Comment by dvirsky** [comment]
The change to the creation was actually good, it made sure no path is left without weights. However storing the weights in the readers is redundant. I thought we'll need it but now it seems we don't. We can remove that. The records are pre-populated with their weights at the beginning and that doesn't change during execution.

**Comment by dvirsky** [comment]
I'll leave that as an exercise for you after I'm gone. Let's just merge
this now :)

**Pull request merged**
